### ISSUE TITLE
Initial Groupsync missing

### ISSUE THREAD

**Issue by MoritzJT** [tgalal/wazapp#142] opened 2012-10-10 17:22 UTC
Current behaviour

Starting off a fresh database:

No groups are synced

After receiving a message from a group, the group is added to the database but it's not automatically pulling groupdetails like image and so on, sometimes does but not regularly

Correct behaviour:

Wazapp starts off a new database / hidden / deleted group

All groups sync without receiving a message first so they can be administered or left without any initial messaging necessary.

**Comment by tgalal** [comment] 2012-10-22 18:58
duplicate of #126

**Closed as completed by tgalal** 2012-10-22 18:58 UTC
